### ISSUE TITLE
A few tweaks to you January 25th assignment

### ISSUE THREAD

**Issue by natenolting** [lwtucci/BUAD-3283#2]
https://github.com/lwtucci/BUAD-3283/blob/7375a19af79bca084a3490542bc48e4ae2d525a5/assignments/january_25/index.html

- [x] Generally, it's bad practice to have your file start with white space. Remove the extra lines at the top of your file.
- [x] Use the HTML5 doctype `<!DOCTYPE html>`. See https://stackoverflow.com/a/10963261
- [x] Upload your work to your hosting account

**Comment by lwtucci** [comment]
All issues corrected and work uploaded to my hosting account: http://mnwildfan12.x10host.com/assignments/

**Comment by natenolting** [comment]
Nice, great job!
